export const LOG_IN_UPDATE_FIELD = "LOG_IN_UPDATE_FIELD";
export const LOG_IN_PAGE_UNLOADED = "LOG_IN_PAGE_UNLOADED";

export const MAJOR_GRID_UPDATE_COLUMNS = "MAJOR_GRID_UPDATE_COLUMNS";
export const MAJOR_GRID_UPDATE_DATA = "MAJOR_GRID_UPDATE_DATA";
export const MAJOR_GRID_UPDATE_SHOW_COLUMN_OPTIONS_MODAL =
  "MAJOR_GRID_UPDATE_SHOW_COLUMN_OPTIONS_MODAL";

export const COLUMN_OPTIONS_CHANGE_COLUMNS = "COLUMN_OPTIONS_CHANGE_COLUMNS";
export const COLUMN_OPTIONS_ADD_COLUMNS = "COLUMN_OPTIONS_ADD_COLUMNS";
export const COLUMN_OPTIONS_DELETE_COLUMNS = "COLUMN_OPTIONS_DELETE_COLUMNS";
export const COLUMN_OPTIONS_SET_ALL_COLUMNS = "COLUMN_OPTIONS_SET_ALL_COLUMNS";
export const COLUMN_OPTIONS_SET_COLUMNS = "COLUMN_OPTIONS_SET_COLUMNS";
